import { NgModule } from "@angular/core";
import {
  MatFormFieldModule,
  MatButtonModule,
  MatCardModule ,
  MatInputModule,
  MatToolbarModule,
  MatExpansionModule,
  MatProgressSpinnerModule,
  MatPaginatorModule,
  MatDialogModule,
  MatSelectModule,
  MatOptionModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatDividerModule,
  MatTableModule,
  MatTabsModule,
  MatRadioModule,
  MatIconModule,
  MatCheckboxModule,
  MatListModule,
  MatTooltipModule,
  MatTreeModule,
  MatRippleModule,
  MatSliderModule,
  MatStepperModule,
  MatButtonToggleModule,
  MatSlideToggleModule,

} from '@angular/material';

@NgModule({
  exports: [
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatToolbarModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatDialogModule,
    MatSelectModule,
    MatOptionModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatDividerModule,
    MatTableModule,
    MatTabsModule,
    MatRadioModule,
    MatIconModule,
    MatCheckboxModule,
    MatListModule,
    MatTooltipModule,
    MatTreeModule,
    MatRippleModule,
    MatSliderModule,
    MatStepperModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
  ]
})
export class AngularMaterialModule {}
